schemaVersion: "0.0.1"
kind: "studio-config"
session:
    description: "Seqera Studio Xpra"
    template:
        kind: "registry"
        registry: "public.cr.seqera.io/platform/data-studio-xpra:6.2.0-r2-1-0.12.0"
        # kind: "dockerfile"        <-- uncomment if you want to customize the image
        # dockerfile: "Dockerfile"  <-- path to your custom Dockerfile
